server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Django application logs
  - job_name: django
    static_configs:
      - targets:
          - localhost
        labels:
          job: django
          service: taruvi-django
          environment: development
          __path__: /var/log/app/django.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            module: module
            correlation_id: correlation_id
      - timestamp:
          source: timestamp
          format: Unix
      - labels:
          level:
          module:
          correlation_id:

  # Celery logs
  - job_name: celery
    static_configs:
      - targets:
          - localhost
        labels:
          job: celery
          service: taruvi-celery
          environment: development
          __path__: /var/log/app/celery.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            correlation_id: correlation_id
      - timestamp:
          source: timestamp
          format: Unix
      - labels:
          level:
          correlation_id:

  # Security logs
  - job_name: security
    static_configs:
      - targets:
          - localhost
        labels:
          job: security
          service: taruvi-security
          environment: development
          __path__: /var/log/app/security.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            event_type: event_type
            correlation_id: correlation_id
      - timestamp:
          source: timestamp
          format: Unix
      - labels:
          level:
          event_type:
          correlation_id:

  # API logs
  - job_name: api
    static_configs:
      - targets:
          - localhost
        labels:
          job: api
          service: taruvi-api
          environment: development
          __path__: /var/log/app/api.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            method: method
            status_code: status_code
            correlation_id: correlation_id
      - timestamp:
          source: timestamp
          format: Unix
      - labels:
          level:
          method:
          status_code:
          correlation_id:

  # Docker container logs
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log
    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            time: time
      - timestamp:
          source: time
          format: RFC3339Nano
      - labels:
          stream: