global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'taruvi-monitor'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /prometheus/metrics

  # Django Application
  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Adjust for your setup
    metrics_path: /api/metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Node Exporter (System Metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Jaeger Metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: /metrics

  # Celery Flower (if using)
  - job_name: 'celery-flower'
    static_configs:
      - targets: ['host.docker.internal:5555']  # Adjust for your setup
    metrics_path: /metrics